name: Release engraved scores

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  engrave_scores:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/edition-esser-skala/ees-tools:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Engrave
        run: make -B works

      - name: Compress MIDI files
        run: zip -r final/midi_collection.zip midi/.

      - name: Publish via rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete
          path: final/
          remote_path: html/edition/assets/pdf/haydn-m-proprium-missae/
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
